### ISSUE TITLE
Requirements.txt not complete

### ISSUE THREAD

**Issue by m3kwong** [bhaskatripathi/pdfGPT#13]
It was missing fitz and frontend.

**Comment by JackChow6** [comment]
i also find this question，good

**Comment by Throwfox** [comment]
> i also find this question，good
PyMuPDF may handle the fitz

**Comment by topherbuckley** [comment]
Can you please reopen this issue. I've tried installing via docker and pip, and the dependencies are backtracking so far I'm already at 20+ minutes for installing dependencies. Can you just run `pip freeze > requirements.txt` on a working environment, commit and merge that requirements.txt please? It'd save us all a bunch of bandwidth and time. Otherwise looking forward to trying this out! cheers!
