### ISSUE TITLE
error cant create file already exists

### ISSUE THREAD

**Issue by xaccell** [bhaskatripathi/pdfGPT#8]
Everytime I try to load a local PDF, it answers the first question, but after that it errors out with "cant create file that already exists".

**Comment by bhaskatripathi** [comment]
could you please try now. I had added a temporary embeddings file which was causing this error. Now I am able to run it correctly:
![image](https://user-images.githubusercontent.com/35177508/232324243-c6e47b6d-a156-452b-a63d-4bab295c60a9.png)

**Comment by xaccell** [comment]
Did you fix the source code also so I could try it locally?

**Comment by bhaskatripathi** [comment]
yes, please get the latest code

**Comment by zerickk** [comment]
> Please use this file https://huggingface.co/spaces/bhaskartripathi/pdfChatter/blob/main/app.py

Thank you. I just tried and still have the same error.

**Comment by bhaskatripathi** [comment]
The error you are getting is because the earlier code was checking if the embedding is created and save temporarily,  it is not reloaded.  This can save the computational effort of creating embedding on every call. However,  as that code had some issue, I had removed that from the latest version.  It looks like you are still using the previous code. Could you plz do a viewdiff ?

**Comment by zerickk** [comment]
I just copied the text from the link you sent and ran it. It has the changes indicated by hugginface on lines 52 and 188.
Line 52: chunk = f'[Page no. {idx+start_page}]' + ' ' + '"' + chunk + '"'
Is this the correct version?

**Comment by bhaskatripathi** [comment]
Yes that is correct

**Comment by xaccell** [comment]
the error still happens after a while

**Comment by bhaskatripathi** [comment]
I have tried it again and again but Not able to replicate it anymore.
